spring.application.name=ticket-orbit

####################database
spring.datasource.url=jdbc:postgresql://localhost:5433/ticketorbitdb
spring.datasource.username = ${DATABASE_USERNAME:postgres}
spring.datasource.password=  ${DATABASE_PASSWORD:mycustompass}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
server.port=8081

####################Security
#default http-basics password
spring.security.user.password=mycustomsecuritypass
