spring.application.name=ticket-orbit

####################database
spring.datasource.url=jdbc:postgresql://localhost:5433/${DATABASE_NAME}
spring.datasource.username = ${DATABASE_USERNAME}
spring.datasource.password = ${DATABASE_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
server.port=8081

####################Security
#default http-basics password
spring.security.user.password=${DEFAULT_SECURITY_PASSWORD}

####################Docker
spring.docker.compose.lifecycle-management=start_and_stop

####################Configuring to use .env file values
spring.config.import=optional:file:.env[.properties]
